/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dc_login;
import org.json.JSONObject;
import ClientServer.ServerConnection;

import javax.swing.JRadioButton;
/**
 *
 * @author HyeonGyu
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form sign
     */
    public Signup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        Dialog = new javax.swing.JDialog();
        ok = new javax.swing.JButton();
        msg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb_subtitle = new javax.swing.JLabel();
        lb_title = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb_discription = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        lb_name = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        lb_grade = new javax.swing.JLabel();
        lb_dpt = new javax.swing.JLabel();
        lb_security = new javax.swing.JLabel();
        btn_sighup = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        lb_passwd1 = new javax.swing.JLabel();
        lb_passwd2 = new javax.swing.JLabel();
        radio_student = new javax.swing.JRadioButton();
        radio_manager = new javax.swing.JRadioButton();
        passwd1 = new javax.swing.JPasswordField();
        passwd2 = new javax.swing.JPasswordField();
        combo_grade = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        MissNum = new javax.swing.JTextField();
        combo_dpt = new javax.swing.JComboBox<>();

        Dialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Dialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Dialog.setModal(true);

        ok.setText("확인");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setText("서버에서 받는 메시지 입니다.");

        javax.swing.GroupLayout DialogLayout = new javax.swing.GroupLayout(Dialog.getContentPane());
        Dialog.getContentPane().setLayout(DialogLayout);
        DialogLayout.setHorizontalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLayout.createSequentialGroup()
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(DialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        DialogLayout.setVerticalGroup(
            DialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ok)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        lb_subtitle.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lb_subtitle.setText("회원가입");

        lb_title.setFont(new java.awt.Font("맑은 고딕", 1, 24)); // NOI18N
        lb_title.setText("수강신청 프로그램");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_title, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_subtitle)
                        .addGap(76, 76, 76)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_subtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        lb_discription.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_discription.setText("회원가입을 위한 기본정보 입력");

        lb_id.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_id.setText("학번");

        id.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        id.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        id.setToolTipText("학번을 조회해주세요");

        lb_name.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_name.setText("이름");

        name.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        lb_grade.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_grade.setText("학년");

        lb_dpt.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_dpt.setText("소속");

        lb_security.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_security.setText("권한");

        btn_sighup.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        btn_sighup.setText("회원가입");
        btn_sighup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sighupActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        btn_reset.setText("초기화");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        lb_passwd1.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_passwd1.setText("비밀번호");

        lb_passwd2.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        lb_passwd2.setText("비밀번호 확인");

        radioGroup.add(radio_student);
        radio_student.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        radio_student.setSelected(true);
        radio_student.setText("학생");
        radio_student.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        radioGroup.add(radio_manager);
        radio_manager.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        radio_manager.setText("관리자");
        radio_manager.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        passwd1.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        passwd2.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N

        combo_grade.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        combo_grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1학년", "2학년", "3학년", "4학년" }));
        combo_grade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combo_grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_gradeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel1.setText("당신의 보물 1호는?");

        MissNum.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        MissNum.setToolTipText("비밀번호 찾기시 필요한 본인인증 메시지입니다.");

        combo_dpt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "소프트웨어융합대학", "빅데이터", "스마트IOT", "콘텐츠IT" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(MissNum, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lb_security, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(radio_student)
                                    .addGap(51, 51, 51)
                                    .addComponent(radio_manager, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(13, 13, 13))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lb_passwd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_passwd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwd1)
                                        .addComponent(passwd2)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lb_grade, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                        .addComponent(lb_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lb_dpt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name)
                                        .addComponent(combo_grade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(combo_dpt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lb_id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(lb_discription)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_sighup, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_discription)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_id))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_passwd1)
                    .addComponent(passwd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_passwd2)
                    .addComponent(passwd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_grade)
                    .addComponent(combo_grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dpt)
                    .addComponent(combo_dpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_security)
                    .addComponent(radio_student)
                    .addComponent(radio_manager))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MissNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btn_sighup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_reset)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>                        

    private void btn_sighupActionPerformed(java.awt.event.ActionEvent evt) {                                           
       if(!CheckBlank()){// 빈칸확인
           showDialog("Error","빈칸을 모두 채워주세요");
           return;
       }
       else if(!CheckPasswd()){ // 비밀번호 일치여부 확인
           passwd1.setText("");
           passwd2.setText("");
           showDialog("Error", "비밀번호가 일치하지 않습니다.");
           return;
       }
       
       String id = this.id.getText();
       String passwd1 = String.valueOf(this.passwd1.getPassword());
       String passwd2 = String.valueOf(this.passwd2.getPassword());
       String name = this.name.getText();
       int grade = combo_grade.getSelectedIndex()+1; // index + 1 = 학년
       String dpt = (String) combo_dpt.getSelectedItem();
       int security = -1; // 학생0, 관리자1
       if(radio_manager.isSelected()){ // 학생0, 관리자1
           security = 1; // 관리자
       }
       else if(radio_student.isSelected()){
           security = 0; // 학생
       }
       String missNum = this.MissNum.getText();
       
       // 서버로 보낼 JSON데이터
       JSONObject data = new JSONObject();
       data.put("command", "register");
       data.put("id", id);
       data.put("passwd", passwd1);
       data.put("name", name);
       data.put("missNum", missNum);
       data.put("dpt", dpt);
       data.put("grade", grade);
       data.put("grade", grade);
       data.put("security", security);
       
       // 서버요청 및 응답
       JSONObject result = new ServerConnection().request(data);
     
       boolean res = result.getBoolean("result");
       String fromMessage = result.getString("message");
       
       if(res) {
           showDialog("Success", "회원가입에 성공하였습니다.");
           this.dispose(); // 회원가입 후 창닫기
       }
       else{
           showDialog("Error", fromMessage);
       }      
       
    }                                          
    
    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {                                          
        reset();
    }                                         

    private void combo_gradeActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void okActionPerformed(java.awt.event.ActionEvent evt) {                                   
        Dialog.dispose();
    }                                  

    public void showDialog(String info, String msg){ // 서버에서 받은 Message Modal Dialog 출력
        Dialog.setTitle(info); // title지정
        this.msg.setText(msg); //메세지 지정
        Dialog.pack();
        Dialog.setLocationRelativeTo(null);
        Dialog.setVisible(true);
    }
    
    public boolean CheckBlank() { // 빈칸확인
        if(id.getText().equals("") || String.valueOf(passwd1.getPassword()).equals("") || String.valueOf(passwd2.getPassword()).equals("") || name.getText().equals("") || MissNum.getText().equals("")){
            return false;
        }
        return true;
    }
    
    
    public boolean CheckPasswd(){ // passwd 일치여부확인
        String passwd1 = String.valueOf(this.passwd1.getPassword());
        String passwd2 = String.valueOf(this.passwd2.getPassword());
        return passwd1.equals(passwd2) ? true : false;
    }
    /**
     * @param args the command line arguments
     */
    
    public void reset(){ // textField 초기화
        id.setText("");
        passwd1.setText("");
        passwd2.setText("");
        name.setText("");
        combo_grade.setSelectedIndex(0);
        combo_dpt.setSelectedIndex(0);
        radioGroup.setSelected(radio_student.getModel(), true);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JDialog Dialog;
    private javax.swing.JTextField MissNum;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_sighup;
    private javax.swing.JComboBox<String> combo_dpt;
    private javax.swing.JComboBox<String> combo_grade;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_discription;
    private javax.swing.JLabel lb_dpt;
    private javax.swing.JLabel lb_grade;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_name;
    private javax.swing.JLabel lb_passwd1;
    private javax.swing.JLabel lb_passwd2;
    private javax.swing.JLabel lb_security;
    private javax.swing.JLabel lb_subtitle;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel msg;
    private javax.swing.JTextField name;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField passwd1;
    private javax.swing.JPasswordField passwd2;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JRadioButton radio_manager;
    private javax.swing.JRadioButton radio_student;
    // End of variables declaration                   
}
